# Generated by Django 3.1 on 2020-09-01 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20200901_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 10, 0, 47, 490014), editable=False, verbose_name='Updated at'),
        ),
    ]
