# Generated by Django 3.1 on 2020-09-04 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_auto_20200901_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN PROGRESS'), ('ON_HOLD', 'ON HOLD'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 11, 9, 56, 551216), editable=False, verbose_name='Updated at'),
        ),
    ]
